import { PaymentUsage } from "@/config/enum";
import { logo, logoMiniBlue, logos } from "@/utils/assets";

export const drive = ["Хойноо RWD", "Урдаа FWD", "Бүх дугуй 4WD"];
export const engine = ["Бензин", "Дизель", "Хайбрид", "Газ", "Цахилгаан"];
export type CarMark = keyof (typeof cars)[CarBrand]["marks"];
export type CarBrand = keyof typeof cars;
export const gearbox = ["Автомат", "Механик"];
export const cars = {
  Acura: {
    label: "Acura",
    marks: {
      Cl: {
        label: "Cl",
        motor: [2.2, 3.2],
        engine: engine.slice(0, 1),
        gearbox: gearbox.slice(0, 1),
        drive: drive.slice(1, 2),
      },
      // Integra: {
      //   label: "Integra",
      //   motor: [1.5, 2.0],
      //   engine: [engine[0], engine[2]],
      //   gearbox: gearbox,
      //   drive: drive.slice(1, 2),
      // },
    },
  },
  Audi: {
    label: "Audi",
    marks: {
      A3: {
        label: "A3",
        engine: engine.slice(0, 3),
        gearbox: gearbox,
        drive: drive.slice(1, 3),
        motor: [1.0, 2.0],
      },
      A4: {
        label: "A4",
        engine: engine.slice(0, 3),
        gearbox: gearbox,
        drive: drive.slice(1, 2),
        motor: [1.4, 3.0],
      },
      A6: {
        label: "A6",
        engine: engine.slice(0, 3),
        gearbox: gearbox.slice(0, 1),
        drive: drive.slice(2, 3),
        motor: [2.0, 3.0],
      },
      Q7: {
        label: "Q7",
        engine: engine.slice(0, 3),
        gearbox: gearbox.slice(0, 1),
        drive: drive.slice(2, 3),
        motor: [2.0, 4.0],
      },
      busad: {
        label: "busad",
      },
    },
  },
  Baic: {
    label: "Baic",
    marks: {
      Bj40: {
        label: "Bj40",
        engine: engine.slice(0, 2),
        gearbox: gearbox,
        drive: drive.slice(2, 3),
        motor: [2.0, 2.3, "Turbo"],
      },
    },
  },
  // Bestune: {
  //   label: "Bestune",
  //   marks: {
  //     B70: {
  //       label: "B70",
  //       engine: [...engine.slice(0, 2), engine[4]],
  //       gearbox: gearbox.slice(0, 1),
  //       drive: drive.slice(1, 2),
  //       motor: [1.5, 2.0],
  //     },
  //   },
  // },
  Bmw: {
    label: "Bmw",
    marks: {
      "3-seri": {
        label: "3-seri",
        engine: engine.slice(0, 3),
        gearbox: gearbox,
        drive: [drive[0], drive[2]],
        motor: [1.5, 3.0],
      },
      "5-seri": {
        label: "5-seri",
        engine: engine.slice(0, 3),
        gearbox: gearbox.slice(0, 1),
        drive: [drive[0], drive[2]],
        motor: [2.0, 4.4],
      },
      "7-ser": {
        label: "7-ser",
        engine: engine.slice(0, 3),
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [3.0, 6.6],
      },
      X1: {
        label: "X1",
        engine: engine.slice(0, 2),
        gearbox: gearbox.slice(0, 1),
        drive: drive.slice(1),
        motor: [1.5, 2.0],
      },
      X3: {
        label: "X3",
        engine: engine.slice(0, 2),
        gearbox: gearbox.slice(0, 1),
        drive: drive.slice(2),
        motor: [2, 3.0],
      },
      X5: {
        label: "X5",
        engine: engine.slice(0, 2),
        gearbox: gearbox.slice(0, 1),
        drive: drive.slice(2),
        motor: [3, 4.4],
      },
      X6: {
        label: "X6",
        engine: engine.slice(0, 2),
        gearbox: gearbox.slice(0, 1),
        drive: drive.slice(2),
        motor: [3, 4.4],
      },
      busad: {
        label: "busad",
      },
    },
  },
  // Cadillac: {
  //   label: "Cadillac",
  //   marks: {
  //     Cts: {
  //       label: "Cts",
  //       engine: engine.slice(0, 1),
  //       gearbox: gearbox,
  //       drive: [drive[0], drive[2]],
  //       motor: [2.0, 6.2],
  //     },
  //     Escalade: {
  //       label: "Escalade",
  //       engine: [engine[0], engine[2]],
  //       gearbox: gearbox.slice(0, 1),
  //       drive: [drive[0], drive[2]],
  //       motor: [6.2, 6.2],
  //     },
  //     busad: {
  //       label: "busad",
  //     },
  //   },
  // },
  Changan: {
    label: "Changan",
    marks: {
      Cs: {
        label: "Cs",
        engine: engine.slice(0, 1),
        gearbox: gearbox,
        drive: [drive[1], drive[2]],
        motor: [1.5, 2.0],
      },
      "Uni K": {
        label: "Uni K",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [2.0, 2.0, "turbo"],
      },
      Бусад: {
        label: "busad",
      },
    },
  },
  // Chery: {
  //   label: "Chery",
  //   marks: {
  //     "Tiggo 7": {
  //       label: "Tiggo 7",
  //       engine: engine.slice(0, 1),
  //       gearbox: gearbox.slice(0, 1),
  //       drive: [drive[1]],
  //       motor: [1.5, 1.6, "turbo"],
  //     },
  //     "Tiggo 7 Pro": {
  //       label: "Tiggo 7 Pro",
  //       engine: [engine[0], engine[2]],
  //       gearbox: gearbox.slice(0, 1),
  //       drive: [drive[1], drive[2]],
  //       motor: [1.5, 1.6, "turbo"],
  //     },
  //     "Tiggo 7 Pro Max": {
  //       label: "Tiggo 7 Pro Max",
  //       engine: [engine[0], engine[2]],
  //       gearbox: gearbox.slice(0, 1),
  //       drive: [drive[1], drive[2]],
  //       motor: [1.5, 1.6, "turbo"],
  //     },
  //     busad: {
  //       label: "busad",
  //     },
  //   },
  // },
  Chevrolet: {
    label: "Chevrolet",
    marks: {
      // Camaro: {
      //   label: "Camaro",
      //   engine: engine.slice(0, 1),
      //   gearbox: gearbox,
      //   drive: [drive[0]],
      //   motor: [2.0, 6.2],
      // },
      "Captiva Sport": {
        label: "Captiva Sport",
        engine: [engine[0]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[1], drive[2]],
        motor: [2.4, 3.6],
      },
      // Colorado: {
      //   label: "Colorado",
      //   engine: [engine[0], engine[1]],
      //   gearbox: gearbox,
      //   drive: [drive[0], drive[2]],
      //   motor: [2.5, 3.6],
      // },
      Cruze: {
        label: "Cruze",
        engine: [engine[0], engine[1]],
        gearbox: gearbox,
        drive: [drive[1]],
        motor: [1.4, 2.0],
      },
      Tahoe: {
        label: "Tahoe",
        engine: [engine[0]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[0], drive[2]],
        motor: [5.3, 6.2],
      },
      // Trailblazer: {
      //   label: "Trailblazer",
      //   engine: [engine[0], engine[1]],
      //   gearbox: gearbox.slice(0, 1),
      //   drive: [drive[1]],
      //   motor: [1.2, 3.6],
      // },
    },
  },
  // Citroean: {
  //   label: "Citroean",
  //   marks: {
  //     C1: {
  //       label: "C1",
  //       engine: engine.slice(0, 1),
  //       gearbox: gearbox,
  //       drive: drive.slice(1),
  //       motor: [1.0, 1.2],
  //     },
  //   },
  // },
  // Deawoo: {
  //   label: "Deawoo",
  //   marks: {
  //     Rezzo: {
  //       label: "Rezzo",
  //       engine: engine.slice(0, 1),
  //       gearbox: gearbox,
  //       drive: drive.slice(1, 2),
  //       motor: [1.6, 2.0],
  //     },
  //     Busad: {
  //       label: "busad",
  //     },
  //   },
  // },
  Daihatsu: {
    label: "Daihatsu",
    marks: {
      Hijet: {
        label: "Hijet",
        engine: engine.slice(0, 1),
        gearbox: gearbox,
        drive: [drive[0], drive[2]],
        motor: [0.66, 0.66],
      },
      Busad: {
        label: "Busad",
      },
    },
  },
  Dodge: {
    label: "Dodge",
    marks: {
      Challenger: {
        label: "Challenger",
        engine: engine.slice(0, 1),
        gearbox: gearbox,
        drive: [drive[0], drive[2]],
        motor: [3.6, 6.4],
      },
      Pickup: {
        label: "Pickup",
        engine: engine.slice(0, 2),
        gearbox: gearbox,
        drive: [drive[0], drive[2]],
        motor: [3.6, 6.4],
      },
      Busad: {
        label: "Busad",
      },
    },
  },
  Dongfeng: {
    label: "Dongfeng",
    marks: {
      "Forthing T5 Evo": {
        label: "Forthing T5 Evo",
        engine: engine.slice(0, 1),
        gearbox: gearbox.slice(0, 1),
        drive: [drive[1]],
        motor: [1.5, 1.5],
      },
      // "Voyah Free": {
      //   label: "Voyah Free",
      //   engine: engine.slice(0, 1),
      //   gearbox: gearbox.slice(0, 1),
      //   drive: [drive[2]],
      //   motor: [2.0, 2.0],
      // },
    },
  },
  // Fiat: {
  //   label: "Fiat",
  //   marks: {
  //     Busad: {
  //       label: "Busad",
  //     },
  //   },
  // },
  Ford: {
    label: "Ford",
    marks: {
      Escape: {
        label: "Escape",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [1.5, 2.5],
      },
      Explorer: {
        label: "Explorer",
        engine: engine.slice(0, 2),
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [2.3, 3.0],
      },
      F150: {
        label: "F150",
        engine: engine.slice(0, 2),
        gearbox: gearbox,
        drive: [drive[0], drive[2]],
        motor: [3.3, 5.0],
      },
      Mustang: {
        label: "Mustang",
        engine: engine.slice(0, 1),
        gearbox: gearbox,
        drive: [drive[0]],
        motor: [2.3, 5.0],
      },
      Pickup: {
        label: "Pickup",
        engine: engine.slice(0, 2),
        gearbox: gearbox,
        drive: [drive[0], drive[2]],
        motor: [2.0, 5.0],
      },
      Ranger: {
        label: "Ranger",
        engine: engine.slice(0, 2),
        gearbox: gearbox,
        drive: [drive[0], drive[2]],
        motor: [2.2, 3.2],
      },
      "Transit Connect": {
        label: "Transit Connect",
        engine: engine.slice(0, 2),
        gearbox: gearbox,
        drive: [drive[1]],
        motor: [1.5, 2.0],
      },
      Busad: {
        label: "Busad",
      },
    },
  },
  // Foton: {
  //   label: "Foton",
  //   marks: {
  //     Tunland: {
  //       label: "Tunland",
  //       engine: [engine[1]],
  //       gearbox: gearbox.slice(0),
  //       drive: [drive[0], drive[2]],
  //       motor: [2.0, 2.4],
  //     },
  //     "View Cs2": {
  //       label: "View Cs2",
  //       engine: engine.slice(0, 1),
  //       gearbox: gearbox.slice(0),
  //       drive: [drive[1]],
  //       motor: [1.5, 1.5],
  //     },
  //   },
  // },
  Geely: {
    label: "Geely",
    marks: {
      Azkarra: {
        label: "Azkarra",
        engine: [engine[0], engine[2], engine[4]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[1]],
        motor: [1.5, 2.0],
      },
      Coolray: {
        label: "Coolray",
        engine: engine.slice(0, 1),
        gearbox: gearbox.slice(0, 1),
        drive: [drive[1]],
        motor: [1.5, 1.5],
      },
      Monjaro: {
        label: "Monjaro",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [2.0, 2.0],
      },
      Tugella: {
        label: "Tugella",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [2.0, 2.0],
      },
    },
  },
  // Gmc: {
  //   label: "Gmc",
  //   marks: {
  //     Acadia: {
  //       label: "Acadia",
  //       engine: [engine[0]],
  //       gearbox: gearbox.slice(0, 1),
  //       drive: [drive[2]],
  //       motor: [2.5, 3.6],
  //     },
  //     Yukon: {
  //       label: "Yukon",
  //       engine: engine.slice(0, 2),
  //       gearbox: gearbox.slice(0, 1),
  //       drive: [drive[2]],
  //       motor: [5.3, 6.2],
  //     },
  //   },
  // },
  Gwm: {
    label: "Gwm",
    marks: {
      Tank: {
        label: "Tank",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [2.0, 2.4],
      },
    },
  },
  Haval: {
    label: "Haval",
    marks: {
      // "Dargo 4X2": {
      //   label: "Dargo 4X2",
      //   engine: [engine[1]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[1]],
      //   motor: [2.0, 2.5],
      // },
      "H Series": {
        label: "H Series",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.0, 3.0],
      },
      Busad: {
        label: "Busad",
      },
    },
  },
  Honda: {
    label: "Honda",
    marks: {
      // Civic: {
      //   label: "Civic",
      //   engine: [engine[0]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[1]],
      //   motor: [1.5, 2.0],
      // },
      "Cr V": {
        label: "Cr V",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [1.5, 2.4],
      },
      "Cr Z": {
        label: "Cr Z",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(1, 2),
        drive: [drive[1]],
        motor: [1.5, 1.5],
      },
      Fit: {
        label: "Fit",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [1.3, 1.5],
      },
      Hrv: {
        label: "Hrv",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [1.5, 1.8],
      },
      Insight: {
        label: "Insight",
        engine: [engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[1]],
        motor: [1.5, 1.5],
      },
      // Odyssey: {
      //   label: "Odyssey",
      //   engine: [engine[0]],
      //   gearbox: gearbox.slice(0, 1),
      //   drive: [drive[1]],
      //   motor: [2.4, 3.5],
      // },
      Busad: {
        label: "Busad",
      },
    },
  },
  Hummer: {
    label: "Hummer",
    marks: {
      "H 2": {
        label: "H 2",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [3.5, 6.0],
      },
      "H 3": {
        label: "H 3",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.0, 3.7],
      },
    },
  },
  Hyundai: {
    label: "Hyundai",
    marks: {
      Accent: {
        label: "Accent",
        engine: [engine[0], engine[1], engine[3]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [1.3, 1.6],
      },
      Equus: {
        label: "Equus",
        engine: [engine[0], engine[3]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[1]],
        motor: [3.8, 5.0],
      },
      Grandeur: {
        label: "Grandeur",
        engine: [engine[0], engine[3]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [2.4, 3.3],
      },
      "Santa Fe": {
        label: "Santa Fe",
        engine: [engine[0], engine[1], engine[3]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.0, 2.4],
      },
      Sonata: {
        label: "Sonata",
        engine: [engine[0], engine[3]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [1.6, 2.5],
      },
      Starex: {
        label: "Starex",
        engine: [engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[0]],
        motor: [2.5, 3.5],
      },
      Tucson: {
        label: "Tucson",
        engine: [engine[0], engine[1], engine[3]],
        gearbox: gearbox.slice(0),
        drive: [drive[0], drive[2]],
        motor: [1.6, 2.4],
      },
      Busad: {
        label: "Busad",
      },
    },
  },
  Infiniti: {
    label: "Infiniti",
    marks: {
      Fx35: {
        label: "Fx35",
        engine: [engine[0]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [3.5, 3.5],
      },
      // Q45: {
      //   label: "Q45",
      //   engine: [engine[0]],
      //   gearbox: gearbox.slice(0, 1),
      //   drive: [drive[0]],
      //   motor: [4.5, 4.5],
      // },
      // Qx56: {
      //   label: "Qx56",
      //   engine: [engine[1]],
      //   gearbox: gearbox.slice(0, 1),
      //   drive: [drive[2]],
      //   motor: [5.6, 5.6],
      // },
    },
  },
  // Isuzu: {
  //   label: "Isuzu",
  //   marks: {
  //     Bighorn: {
  //       label: "Bighorn",
  //       engine: [engine[1]],
  //       gearbox: gearbox.slice(0),
  //       drive: [drive[2]],
  //       motor: [3.0, 3.5],
  //     },
  //   },
  // },
  Jaguar: {
    label: "Jaguar",
    marks: {
      // "X Type": {
      //   label: "X Type",
      //   engine: [engine[0]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[0], drive[2]],
      //   motor: [2.0, 3.0],
      // },
      Xj: {
        label: "Xj",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[0]],
        motor: [2.7, 5.0],
      },
      Busad: {
        label: "Busad",
      },
    },
  },
  Jeep: {
    label: "Jeep",
    marks: {
      Cherokee: {
        label: "Cherokee",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.4, 3.6],
      },
      "Grand Cherokee": {
        label: "Grand Cherokee",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [3.6, 6.4],
      },
      Wrangler: {
        label: "Wrangler",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.0, 3.6],
      },
      Busad: {
        label: "Busad",
      },
    },
  },
  Kaiyi: {
    label: "Kaiyi",
    marks: {
      "X Series": {
        label: "X Series",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.0, 3.0],
      },
      Busad: {
        label: "Busad",
      },
    },
  },
  Kia: {
    label: "Kia",
    marks: {
      Cadenza: {
        label: "Cadenza",
        engine: [engine[0], engine[3]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[1]],
        motor: [3.3, 3.3],
      },
      Optima: {
        label: "Optima",
        engine: [engine[0], engine[2], engine[3]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [1.6, 2.4],
      },
      Sorento: {
        label: "Sorento",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.2, 3.5],
      },
      Sportage: {
        label: "Sportage",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[1], drive[2]],
        motor: [1.6, 2.4],
      },
      Busad: {
        label: "Busad",
      },
    },
  },
  Lada: {
    label: "Lada",
    marks: {
      Niva: {
        label: "Niva",
        engine: [engine[0]],
        gearbox: gearbox.slice(1, 2),
        drive: [drive[2]],
        motor: [1.7, 1.7],
      },
      // Vesta: {
      //   label: "Vesta",
      //   engine: [engine[0]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[1]],
      //   motor: [1.6, 1.6],
      // },
    },
  },
  "Land Rover": {
    label: "Land Rover",
    marks: {
      Defender: {
        label: "Defender",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.0, 5.0],
      },
      Discovery: {
        label: "Discovery",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.0, 3.0],
      },
      // Freelander: {
      //   label: "Freelander",
      //   engine: [engine[0]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[2]],
      //   motor: [2.0, 2.5],
      // },
      // "Land Rover": {
      //   label: "Land Rover",
      //   engine: [engine[0]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[2]],
      //   motor: [2.0, 5.0],
      // },
      "Range Rover": {
        label: "Range Rover",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.0, 5.0],
      },
    },
  },

  Lexus: {
    label: "Lexus",
    marks: {
      Ct: {
        label: "Ct",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[1]],
        motor: [1.8, 1.8],
      },
      Gs: {
        label: "Gs",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[0]],
        motor: [2.5, 3.5],
      },
      Gx: {
        label: "Gx",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [4.6, 4.6],
      },
      Hs: {
        label: "Hs",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[1]],
        motor: [2.0, 2.0],
      },
      // Is: {
      //   label: "Is",
      //   engine: [engine[0], engine[2]],
      //   gearbox: gearbox.slice(0, 1),
      //   drive: [drive[0]],
      //   motor: [3.5, 5.0],
      // },
      "LX 470": {
        label: "LX 470",
        engine: [engine[0]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [4.7, 4.7],
      },
      "LX 570": {
        label: "LX 570",
        engine: [engine[0]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [5.7, 5.7],
      },
      "LX 600": {
        label: "LX 600",
        engine: [engine[0]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [3.5, 3.5],
      },
      Nx: {
        label: "Nx",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: drive,
        motor: [2.0, 2.5],
      },
      Nx200t: {
        label: "Nx200t",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0, 1),
        //
        drive: drive,
        motor: [2.0, 2.0],
      },
      Nx300h: {
        label: "Nx300h",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0, 1),
        //
        drive: drive,
        motor: [2.5, 2.5],
      },
      Rx: {
        label: "Rx",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [3.5, 3.6],
      },
      Rx200t: {
        label: "Rx200t",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [2.0, 2.0],
      },
      Rx270: {
        label: "Rx270",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [2.7, 2.7],
      },
      Rx270h: {
        label: "Rx270h",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [2.7, 2.7],
      },
      // Rx270t: {
      //   label: "Rx270t",
      //   engine: [engine[0]],
      //   gearbox: gearbox.slice(0, 1),
      //   drive: [drive[2]],
      //   motor: [2.7, 2.7],
      // },
      Rx300h: {
        label: "Rx300h",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [2.0, 2.0],
      },
      Rx330: {
        label: "Rx330",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [3.3, 3.3],
      },
      // Rx330h: {
      //   label: "Rx330h",
      //   engine: [engine[2]],
      //   gearbox: gearbox.slice(0, 1),
      //   drive: [drive[2]],
      //   motor: [2.0, 3.0],
      // },
      Rx350h: {
        label: "Rx350h",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [2.5, 2.7],
      },
      Rx400h: {
        label: "Rx400h",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [3.3, 3.3],
      },
      Rx450h: {
        label: "Rx450h",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [3.3, 3.3],
      },
    },
  },
  // "Li Auto": {
  //   label: "Li Auto",
  //   marks: {
  //     L9: {
  //       label: "L9",
  //       engine: [engine[0]],
  //       gearbox: gearbox.slice(0, 1),
  //       drive: [drive[2]],
  //       motor: [3.5, 3.5],
  //     },
  //     One: {
  //       label: "One",
  //       engine: [engine[0]],
  //       gearbox: gearbox.slice(0, 1),
  //       drive: [drive[2]],
  //       motor: [2.0, 2.0],
  //     },
  //   },
  // },
  // Lincoln: {
  //   label: "Lincoln",
  //   marks: {
  //     "Town Car": {
  //       label: "Town Car",
  //       engine: [engine[0]],
  //       gearbox: gearbox.slice(0, 1),
  //       drive: [drive[0]],
  //       motor: [4.6, 4.6],
  //     },
  //     Busad: {
  //       label: "Busad",
  //     },
  //   },
  // },
  Mazda: {
    label: "Mazda",
    marks: {
      Bongo: {
        label: "Bongo",
        engine: [engine[1]],
        gearbox: gearbox.slice(1, 2),
        drive: [drive[0]],
        motor: [2.0, 2.5],
      },
      Cx: {
        label: "Cx",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.0, 2.5],
      },
      Mazda2: {
        label: "Mazda2",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [1.5, 1.5],
      },
      Mazda3: {
        label: "Mazda3",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [1.6, 2.5],
      },
      // Mazda5: {
      //   label: "Mazda5",
      //   engine: [engine[0]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[1]],
      //   motor: [2.0, 2.5],
      // },
      // Mazda6: {
      //   label: "Mazda6",
      //   engine: [engine[0], engine[1]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[1]],
      //   motor: [2.0, 2.5],
      // },
      // Mpv: {
      //   label: "Mpv",
      //   engine: [engine[0]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[1]],
      //   motor: [2.3, 2.5],
      // },
      Verisa: {
        label: "Verisa",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [1.3, 1.3],
      },
    },
  },
  "Mersedes Benz": {
    label: "Mersedes Benz",
    marks: {
      "C Class": {
        label: "C Class",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[0]],
        motor: [1.6, 3.5],
      },
      "Cla Class": {
        label: "Cla Class",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [1.6, 2.0],
      },
      "E Class": {
        label: "E Class",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[0]],
        motor: [2.0, 4.0],
      },
      "G Class": {
        label: "G Class",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [3.0, 6.0],
      },
      "Gl Class": {
        label: "Gl Class",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [3.0, 5.5],
      },
      "M Class": {
        label: "M Class",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [3.0, 5.5],
      },
      "S Class": {
        label: "S Class",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[0]],
        motor: [2.9, 6.0],
      },
    },
  },
  // Mg: {
  //   label: "Mg",
  //   marks: {
  //     Busad: {
  //       label: "Busad",
  //     },
  //   },
  // },
  Mini: {
    label: "Mini",
    marks: {
      Cooper: {
        label: "Cooper",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [1.5, 2.0],
      },
      Countryman: {
        label: "Countryman",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[1], drive[2]],
        motor: [1.6, 2.0],
      },
      Busad: {
        label: "busad",
      },
    },
  },
  Mitsubishi: {
    label: "Mitsubishi",
    marks: {
      // Airtrek: {
      //   label: "Airtrek",
      //   engine: [engine[0], engine[1]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[2]],
      //   motor: [2.0, 2.4],
      // },
      // Challenger: {
      //   label: "Challenger",
      //   engine: [engine[0]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[0]],
      //   motor: [3.8, 6.4],
      // },
      Colt: {
        label: "Colt",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [1.1, 1.6],
      },
      Delica: {
        label: "Delica",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.0, 2.8],
      },
      // Eclipse: {
      //   label: "Eclipse",
      //   engine: [engine[0]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[1]],
      //   motor: [1.8, 2.4],
      // },
      // Galant: {
      //   label: "Galant",
      //   engine: [engine[0], engine[1]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[1]],
      //   motor: [1.8, 3.8],
      // },
      L200: {
        label: "L200",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.4, 2.5],
      },
      Lancer: {
        label: "Lancer",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[1], drive[2]],
        motor: [1.5, 2.0],
      },
      // Mirage: {
      //   label: "Mirage",
      //   engine: [engine[0]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[1]],
      //   motor: [1.0, 1.2],
      // },
      // Montero: {
      //   label: "Montero",
      //   engine: [engine[0], engine[1]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[2]],
      //   motor: [2.8, 3.8],
      // },
      Outlander: {
        label: "Outlander",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.0, 2.4],
      },
      // Pajero: {
      //   label: "Pajero",
      //   engine: [engine[0], engine[1]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[2]],
      //   motor: [2.4, 3.8],
      // },
      Rvr: {
        label: "Rvr",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [1.8, 2.0],
      },
      Busad: {
        label: "Busad",
      },
    },
  },
  // Neta: {
  //   label: "Neta",
  //   marks: {
  //     Busad: {
  //       label: "Busad",
  //     },
  //   },
  // },
  Nissan: {
    label: "Nissan",
    marks: {
      "370Z": {
        label: "370Z",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[0]],
        motor: [3.7, 3.7],
      },
      Advan: {
        label: "Advan",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[0]],
        motor: [1.6, 2.0],
      },
      // Altima: {
      //   label: "Altima",
      //   engine: [engine[0]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[1]],
      //   motor: [2.5, 3.5],
      // },
      // Armada: {
      //   label: "Armada",
      //   engine: [engine[0]],
      //   gearbox: gearbox.slice(0, 1),
      //   drive: [drive[2]],
      //   motor: [5.6, 5.6],
      // },
      Caravan: {
        label: "Caravan",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.5, 3.5],
      },
      Cube: {
        label: "Cube",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [1.5, 1.5],
      },
      // Datsun: {
      //   label: "Datsun",
      //   engine: [engine[0]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[0], drive[1]],
      //   motor: [1.0, 1.6],
      // },
      Elgrand: {
        label: "Elgrand",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [2.5, 3.5],
      },
      Fuga: {
        label: "Fuga",
        engine: [engine[0]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[0]],
        motor: [2.5, 3.5],
      },
      Juke: {
        label: "Juke",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[1], drive[2]],
        motor: [1.6, 2.0],
      },
      // Latio: {
      //   label: "Latio",
      //   engine: [engine[0]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[1]],
      //   motor: [1.2, 1.8],
      // },
      Leaf: {
        label: "Leaf",
        engine: [engine[4]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[1]],
        // tsahilgaan
        motor: [2.4, 3.8],
      },
      // March: {
      //   label: "March",
      //   engine: [engine[0]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[1]],
      //   motor: [1.0, 1.6],
      // },
      Murano: {
        label: "Murano",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [2.5, 3.5],
      },
      Navara: {
        label: "Navara",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.3, 3.0],
      },
      Note: {
        label: "Note",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [1.2, 1.6],
      },
      Nv200: {
        label: "Nv200",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [1.5, 2.0],
      },
      Pathfinder: {
        label: "Pathfinder",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.5, 4.0],
      },
      Patrol: {
        label: "Patrol",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.8, 5.6],
      },
      // Presage: {
      //   label: "Presage",
      //   engine: [engine[0]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[1]],
      //   motor: [2.0, 2.5],
      // },
      Qashqai: {
        label: "Qashqai",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[1], drive[2]],
        motor: [1.2, 2.0],
      },
      // Rnessa: {
      //   label: "Rnessa",
      //   engine: [engine[0]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[1]],
      //   motor: [2.0, 2.5],
      // },
      Serena: {
        label: "Serena",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.0, 2.5],
      },
      Skyline: {
        label: "Skyline",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[0]],
        motor: [2.0, 3.5],
      },
      Sunny: {
        label: "Sunny",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [1.3, 1.6],
      },
      Teana: {
        label: "Teana",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [2.0, 3.5],
      },
      Tiida: {
        label: "Tiida",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [1.5, 1.8],
      },
      Vanetta: {
        label: "Vanetta",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [1.3, 2.0],
      },
      // Versa: {
      //   label: "Versa",
      //   engine: [engine[0]],
      //   gearbox: gearbox.slice(0, 1),
      //   drive: [drive[1]],
      //   motor: [1.6, 1.8],
      // },
      Wingroad: {
        label: "Wingroad",
        engine: [engine[0]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[1]],
        motor: [1.5, 1.8],
      },
      "X Trail": {
        label: "X Trail",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [1.6, 2.5],
      },
      Xterra: {
        label: "Xterra",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.4, 4.0],
      },
      Busad: {
        label: "Busad",
      },
    },
  },
  // Peugeot: {
  //   label: "Peugeot",
  //   marks: {
  //     Busad: {
  //       label: "Busad",
  //     },
  //   },
  // },
  Porsche: {
    label: "Porsche",
    marks: {
      Cayenne: {
        label: "Cayenne",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [3.0, 4.8],
      },
      // Cayman: {
      //   label: "Cayman",
      //   engine: [engine[0]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[0]],
      //   motor: [2.7, 4.0],
      // },
      Macan: {
        label: "Macan",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [2.0, 3.6],
      },
      Panamera: {
        label: "Panamera",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [2.9, 4.0],
      },
      Busad: {
        label: "Busad",
      },
    },
  },
  // Renault: {
  //   label: "Renault",
  //   marks: {
  //     Busad: {
  //       label: "Busad",
  //     },
  //   },
  // },
  Samsung: {
    label: "Samsung",
    marks: {
      Qm: {
        label: "Qm",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.0, 2.3],
      },
      // Sm: {
      //   label: "Sm",
      //   engine: [engine[0], engine[1]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[2]],
      //   motor: [2.0, 2.7],
      // },
    },
  },
  Ssangyong: {
    label: "Ssangyong",
    marks: {
      Actyon: {
        label: "Actyon",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.0, 2.8],
      },
      Istana: {
        label: "Istana",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[0]],
        motor: [2.0, 2.5],
      },
      Musso: {
        label: "Musso",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.9, 3.2],
      },
      Rexton: {
        label: "Rexton",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.7, 3.2],
      },
      // "Rodius Stavic": {
      //   label: "Rodius Stavic",
      //   engine: [engine[0], engine[1]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[0]],
      //   motor: [2.7, 3.2],
      // },
      Busad: {
        label: "Busad",
      },
    },
  },
  Subaru: {
    label: "Subaru",
    marks: {
      Exiga: {
        label: "Exiga",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.0, 5.0],
      },
      Forester: {
        label: "Forester",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.0, 2.5],
      },
      Impreza: {
        label: "Impreza",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[1], drive[2]],
        motor: [1.5, 2.5],
      },
      Legacy: {
        label: "Legacy",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[1], drive[2]],
        motor: [2.0, 3.6],
      },
      // Liberty: {
      //   label: "Liberty",
      //   engine: [engine[0], engine[1]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[1], drive[2]],
      //   motor: [2.0, 3.0],
      // },
      Outback: {
        label: "Outback",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.0, 3.6],
      },
      // Trezia: {
      //   label: "Trezia",
      //   engine: [engine[0]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[1]],
      //   motor: [1.3, 1.3],
      // },
      Wrx: {
        label: "Wrx",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.0, 2.5],
      },
      "Wrx Sti": {
        label: "Wrx Sti",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.5, 2.5],
      },
      Xt: {
        label: "Xt",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [1.8, 2.7],
      },
      "Xv Crosstrek": {
        label: "Xv Crosstrek",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [1.6, 2.0],
      },
      Busad: {
        label: "Brand",
      },
    },
  },
  Suzuki: {
    label: "Suzuki",
    marks: {
      // Aerio: {
      //   label: "Aerio",
      //   engine: [engine[0]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[1]],
      //   motor: [1.3, 1.6],
      // },
      Escudo: {
        label: "Escudo",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [1.6, 2.5],
      },
      // "Grand Vitara": {
      //   label: "Grand Vitara",
      //   engine: [engine[0], engine[1]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[2]],
      //   motor: [2.0, 2.4],
      // },
      Hustler: {
        label: "Hustler",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [0.6, 1.2],
      },
      Jimny: {
        label: "Jimny",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [1.3, 1.5],
      },
      Swift: {
        label: "Swift",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [1.2, 1.6],
      },
      // Sx4: {
      //   label: "Sx4",
      //   engine: [engine[0], engine[1]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[2]],
      //   motor: [1.2, 1.6],
      // },
      Busad: {
        label: "Brand",
      },
    },
  },
  Tesla: {
    label: "Tesla",
    marks: {
      Models: {
        label: "Models",
        engine: [engine[4]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        // tsahilgaan
        motor: [1.3, 1.6],
      },
      Modely: {
        label: "Modely",
        engine: [engine[4]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        // tsahilgaan
        motor: [1.3, 1.6],
      },
      Busad: {
        label: "Brand",
      },
    },
  },
  Toyota: {
    label: "Toyota",
    marks: {
      "4Runner": {
        label: "4Runner",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.7, 4.0],
      },
      Allion: {
        label: "Allion",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[1]],
        motor: [1.5, 2.0],
      },
      Alphard: {
        label: "Alphard",
        engine: [engine[0], engine[1], engine[2]],
        gearbox: gearbox.slice(0),
        drive: [drive[1], drive[2]],
        motor: [2.4, 3.5],
      },
      Aqua: {
        label: "Aqua",
        engine: [engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[1]],
        motor: [1.5, 1.5],
      },
      Auris: {
        label: "Auris",
        engine: [engine[0], engine[1], engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[1]],
        motor: [1.5, 1.8],
      },
      Avalon: {
        label: "Avalon",
        engine: [engine[0], engine[1], engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[1]],
        motor: [2.5, 3.5],
      },
      Avensis: {
        label: "Avensis",
        engine: engine.slice(0, 3),
        gearbox: gearbox.slice(0),
        drive: [drive[1], drive[2]],
        motor: [1.6, 2.4],
      },
      Axio: {
        label: "Axio",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0),
        drive: [drive[1], drive[2]],
        motor: [1.3, 1.8],
      },
      // Bb: {
      //   label: "Bb",
      //   engine: [engine[0]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[1]],
      //   motor: [1.3, 1.5],
      // },
      // Brevis: {
      //   label: "Brevis",
      //   engine: [engine[0]],
      //   gearbox: gearbox.slice(0, 1),
      //   drive: [drive[1]],
      //   motor: [2.5, 3.0],
      // },
      // Caldina: {
      //   label: "Caldina",
      //   engine: [engine[0], engine[1]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[1]],
      //   motor: [1.8, 2.0],
      // },
      Camry: {
        label: "Camry",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [2.4, 3.5],
      },
      // Celica: {
      //   label: "Celica",
      //   engine: [engine[0]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[1]],
      //   motor: [1.8, 2.0],
      // },
      // Chaser: {
      //   label: "Chaser",
      //   engine: [engine[0]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[0]],
      //   motor: [1.8, 2.0],
      // },
      Chr: {
        label: "Chr",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [1.8, 1.8],
      },
      Corolla: {
        label: "Corolla",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [1.6, 2.0],
      },
      // "Corolla Cross": {
      //   label: "Corolla Cross",
      //   engine: [engine[0], engine[2]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[2]],
      //   motor: [1.8, 2.0],
      // },
      // Cresta: {
      //   label: "Cresta",
      //   engine: [engine[0]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[0]],
      //   motor: [2.0, 2.5],
      // },
      Crown: {
        label: "Crown",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0),
        drive: [drive[0]],
        motor: [2.0, 3.5],
      },
      // "Crown Cluger": {
      //   label: "Crown Cluger",
      //   engine: [engine[0], engine[2]],
      //   gearbox: gearbox.slice(0, 1),
      //   drive: [drive[2]],
      //   motor: [2.4, 3.5],
      // },
      Esquire: {
        label: "Esquire",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[0]],
        motor: [2, 2.5],
      },
      Estima: {
        label: "Estima",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.4, 3.5],
      },
      Fielder: {
        label: "Fielder",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[0]],
        motor: [1.5, 1.8],
      },
      "Fj Cruiser": {
        label: "Fj Cruiser",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [4.0, 4.0],
      },
      // Jaia: {
      //   label: "Jaia",
      //   engine: [engine[0]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[2]],
      //   motor: [2.0, 2.4],
      // },
      // Granvia: {
      //   label: "Granvia",
      //   engine: [engine[0]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[0]],
      //   motor: [2.4, 3.0],
      // },
      Harrier: {
        label: "Harrier",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.0, 3.5],
      },
      Hiace: {
        label: "Hiace",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[0]],
        motor: [2.0, 3.0],
      },
      Highlander: {
        label: "Highlander",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.5, 3.5],
      },
      Hilux: {
        label: "Hilux",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.4, 3.0],
      },
      Ipsum: {
        label: "Ipsum",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [2.0, 2.4],
      },
      Isis: {
        label: "Isis",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [1.8, 2.0],
      },
      Ist: {
        label: "Ist",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [1.3, 1.5],
      },
      Kluger: {
        label: "Kluger",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.4, 3.5],
      },
      "Land Cruiser 100": {
        label: "Land Cruiser 100",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [4.0, 4.5],
      },
      "Land Cruiser 105": {
        label: "Land Cruiser 105",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(1, 2),
        drive: [drive[2]],
        motor: [4.2, 4.2],
      },
      "Land Cruiser 200": {
        label: "Land Cruiser 200",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [4.0, 4.5],
      },
      "Land Cruiser 300": {
        label: "Land Cruiser 300",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [3.5, 4.5],
      },
      "Land Cruiser 70": {
        label: "Land Cruiser 70",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(1, 2),
        drive: [drive[2]],
        motor: [4.0, 4.5],
      },
      "Land Cruiser 77": {
        label: "Land Cruiser 77",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(1, 2),
        drive: [drive[2]],
        motor: [4.0, 4.0],
      },
      "Land Cruiser 80": {
        label: "Land Cruiser 80",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.7, 3.0],
      },
      "Land Cruiser Prado": {
        label: "Land Cruiser Prado",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.7, 3.0],
      },
      "Land Cruiser Prado 120": {
        label: "Land Cruiser Prado 120",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.7, 3.0],
      },
      "Land Cruiser Prado 150": {
        label: "Land Cruiser Prado 150",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.7, 3.0],
      },
      "Land Cruiser Prado 250": {
        label: "Land Cruiser Prado 250",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.7, 3.0],
      },
      // "Land Cruiser Prado 90": {
      //   label: "Land Cruiser Prado 90",
      //   engine: [engine[0], engine[1]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[2]],
      //   motor: [2.7, 3.0],
      // },
      "Land Cruiser Prado 95": {
        label: "Land Cruiser Prado 95",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.7, 3.0],
      },
      Mark: {
        label: "Mark",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [1.8, 3.0],
      },
      // "Mark 2": {
      //   label: "Mark 2",
      //   engine: [engine[0], engine[1]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[0]],
      //   motor: [2.0, 3.0],
      // },
      // Nadia: {
      //   label: "Nadia",
      //   engine: [engine[0]],
      //   gearbox: gearbox.slice(0.1),
      //   drive: [drive[1]],
      //   motor: [1.8, 2.0],
      // },
      Noah: {
        label: "Noah",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [2.0, 2.7],
      },
      Passo: {
        label: "Passo",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [1.0, 1.3],
      },
      Porte: {
        label: "Porte",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [1.0, 1.3],
      },
      Premio: {
        label: "Premio",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [1.5, 2.0],
      },
      "Prius 10,11": {
        label: "Prius 10,11",
        engine: [engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[1]],
        motor: [1.5, 1.5],
      },
      "Prius 20": {
        label: "Prius 20",
        engine: [engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[1]],
        motor: [1.5, 1.5],
      },
      "Prius 30": {
        label: "Prius 30",
        engine: [engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[1]],
        motor: [1.8, 1.8],
      },
      "Prius 35": {
        label: "Prius 35",
        engine: [engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[1]],
        motor: [1.8, 1.8],
      },
      "Prius 40": {
        label: "Prius 40",
        engine: [engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[1]],
        motor: [1.8, 1.8],
      },
      "Prius 41": {
        label: "Prius 41",
        engine: [engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[1]],
        motor: [1.8, 1.8],
      },
      "Prius 50": {
        label: "Prius 50",
        engine: [engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[1]],
        motor: [1.8, 1.8],
      },
      "Prius 51": {
        label: "Prius 51",
        engine: [engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[1]],
        motor: [1.8, 1.8],
      },
      "Prius 55": {
        label: "Prius 55",
        engine: [engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[1]],
        motor: [1.8, 1.8],
      },
      "Prius 52": {
        label: "Prius 52",
        engine: [engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[1]],
        motor: [1.8, 1.8],
      },
      Probox: {
        label: "Probox",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [1.3, 1.5],
      },
      Ractis: {
        label: "Ractis",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [1.3, 1.5],
      },
      Raum: {
        label: "Raum",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [1.5, 1.5],
      },
      Rav4: {
        label: "Rav4",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.0, 2.5],
      },
      Rumion: {
        label: "Rumion",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [1.8, 1.8],
      },
      Rush: {
        label: "Rush",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [1.5, 1.5],
      },
      Sai: {
        label: "Sai",
        engine: [engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[1]],
        motor: [2.4, 2.4],
      },
      Sequoia: {
        label: "Sequoia",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [4.6, 5.7],
      },
      Sienna: {
        label: "Sienna",
        engine: [engine[0]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [2.7, 3.5],
      },
      Sienta: {
        label: "Sienta",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [1.5, 1.5],
      },
      Spacio: {
        label: "Spacio",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [1.5, 1.5],
      },
      Succeed: {
        label: "Succeed",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [1.5, 1.5],
      },
      Tacoma: {
        label: "Tacoma",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.7, 4.0],
      },
      Townace: {
        label: "Townace",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.0, 2.7],
      },
      Tundra: {
        label: "Tundra",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [4.6, 5.7],
      },
      Vanguard: {
        label: "Vanguard",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[2]],
        motor: [2.4, 3.5],
      },
      Vellfire: {
        label: "Vellfire",
        engine: [engine[0]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [2.4, 3.5],
      },
      // Venza: {
      //   label: "Venza",
      //   engine: [engine[0], engine[2]],
      //   gearbox: gearbox.slice(0, 1),
      //   drive: [drive[2]],
      //   motor: [2.5, 2.5],
      // },
      Verossa: {
        label: "Verossa",
        engine: [engine[0]],
        gearbox: gearbox.slice(0),
        drive: [drive[0]],
        motor: [2.5, 3.0],
      },
      Vitz: {
        label: "Vitz",
        engine: [engine[0]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[1]],
        motor: [1.0, 1.5],
      },
      Voxy: {
        label: "Voxy",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[1]],
        motor: [2.0, 2.0],
      },
      Wish: {
        label: "Wish",
        engine: [engine[0], engine[2]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [1.8, 2.0],
      },
      // Yaris: {
      //   label: "Yaris",
      //   engine: [engine[0], engine[2]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[1]],
      //   motor: [1.0, 1.5],
      // },
      Busad: {
        label: "Busad",
      },
    },
  },
  Volkswagen: {
    label: "Volkswagen",
    marks: {
      // Beetle: {
      //   label: "Beetle",
      //   engine: [engine[0], engine[1]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[1]],
      //   motor: [1.2, 2.5],
      // },
      // Golf: {
      //   label: "Golf",
      //   engine: [engine[0], engine[1], engine[2]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[1], drive[2]],
      //   motor: [1.0, 2.0],
      // },
      // Jetta: {
      //   label: "Jetta",
      //   engine: [engine[0], engine[1], engine[2]],
      //   gearbox: gearbox.slice(0),
      //   drive: [drive[1]],
      //   motor: [1.4, 2.5],
      // },
      Passat: {
        label: "Passat",
        engine: [engine[0], engine[1], engine[2]],
        gearbox: gearbox.slice(0),
        drive: [drive[1], drive[2]],
        motor: [1.4, 2.0],
      },
      Polo: {
        label: "Polo",
        engine: [engine[0], engine[1]],
        gearbox: gearbox.slice(0),
        drive: [drive[1]],
        motor: [1.0, 1.6],
      },
      Tiguan: {
        label: "Tiguan",
        engine: [engine[0], engine[1], engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [1.4, 2.0],
      },
      Touareg: {
        label: "Touareg",
        engine: [engine[0], engine[1], engine[2]],
        gearbox: gearbox.slice(0, 1),
        drive: [drive[2]],
        motor: [3.0, 4.2],
      },
      // Vanagon: {
      //   label: "Vanagon",
      //   engine: [engine[0], engine[1]],
      //   gearbox: gearbox.slice(1, 2),
      //   drive: [drive[0], drive[2]],
      //   motor: [1.6, 2.1],
      // },
      Busad: {
        label: "Busad",
      },
    },
    // Volvo: {
    //   label: "Volvo",
    //   marks: {
    //     Xc60: {
    //       label: "Xc60",
    //       engine: [engine[0], engine[1], engine[2]],
    //       gearbox: gearbox.slice(0, 1),
    //       drive: [drive[2]],
    //       motor: [2.0, 2.5],
    //     },
    //     Xc90: {
    //       label: "Xc90",
    //       engine: [engine[0], engine[1], engine[2]],
    //       gearbox: gearbox.slice(0, 1),
    //       drive: [drive[2]],
    //       motor: [2.0, 2.5],
    //     },
    //   },
    // },
  },
};

export const steerType = [
  {
    label: "Зөв",
    value: "Зөв",
  },
  {
    label: "Буруу",
    value: "Буруу",
  },
];

export const carColor = [
  {
    label: "Бор",
    value: "Бор",
  },
  {
    label: "Боронзон",
    value: "Боронзон",
  },
  {
    label: "Ногоон",
    value: "Ногоон",
  },
  {
    label: "Саарал",
    value: "Саарал",
  },
  {
    label: "Сувдан цагаан",
    value: "Сувдан цагаан",
  },
  {
    label: "Улаан",
    value: "Улаан",
  },
  {
    label: "Улбар шар",
    value: "Улбар шар",
  },
  {
    label: "Хар",
    value: "Хар",
  },
  {
    label: "Хар саарал",
    value: "Хар саарал",
  },
  {
    label: "Хөх",
    value: "Хөх",
  },
  {
    label: "Хүрэн",
    value: "Хүрэн",
  },
  {
    label: "Цагаан",
    value: "Цагаан",
  },
  {
    label: "Цагаан шар",
    value: "Цагаан шар",
  },
  {
    label: "Цайвар цэнхэр",
    value: "Цайвар цэнхэр",
  },
  {
    label: "Цэнхэр",
    value: "Цэнхэр",
  },
  {
    label: "Шар",
    value: "Шар",
  },
  {
    label: "Шаргал",
    value: "Шаргал",
  },
  {
    label: "Ягаан",
    value: "Ягаан",
  },
  {
    label: "Бусад",
    value: "Бусад",
  },
];

export const meterRange = [
  {
    label: "0-30,000 км",
    value: "0-30,000 км",
  },
  {
    label: "30,001-50,000 км",
    value: "30,001-50,000 км",
  },
  {
    label: "50,001-100,000 км",
    value: "50,001-100,000 км",
  },
  {
    label: "100,001км - 150,000км",
    value: "100,001км - 150,000км",
  },
  {
    label: "150,001-200,000 км",
    value: "150,001-200,000 км",
  },
  {
    label: "200,001-250,000 км",
    value: "200,001-250,000 км",
  },
  {
    label: "250,001 км-аас дээш",
    value: "250,001 км-аас дээш",
  },
];

export const type = [
  {
    label: "Жийп",
    value: "Жийп",
  },
  {
    label: "Суудлын тэрэг",
    value: "Суудлын тэрэг",
  },
  {
    label: "Гэр бүлийн",
    value: "Гэр бүлийн",
  },
];
export const conditions = [
  {
    label: "Дугаар авсан",
    value: "Дугаар авсан",
  },
  {
    label: "00 гүйлттэй",
    value: "00 гүйлттэй",
  },
  {
    label: "Дугаар аваагүй",
    value: "Дугаар аваагүй",
  },
];

export const carMain = [
  { key: "color", data: carColor },
  { key: "interior", data: carColor },
  { key: "steerType", data: steerType },
  // { key: "type", data: type },
  { key: "conditions", data: conditions },
];

export const carTechnik = ["engine", "motor", "gearbox", "drive"];
export type PaymentValueType = keyof typeof paymentValues;
export type OrgValueType = keyof typeof orgValues;
export const paymentValues = {
  usage: [
    {
      label: "Даатгалын зориулалттай",
      value: PaymentUsage.INSURANCE,
      icon: undefined,
    },
    {
      label: "Зээлийн зориулалттай",
      value: PaymentUsage.LOAN,
      icon: undefined,
    },
    {
      label: "Үнэ цэнийн зориулалттай",
      value: PaymentUsage.VALUE,
      icon: undefined,
    },
  ],
  org: [
    {
      label: "",
      value: 0,
    },
    {
      label: "",
      value: 1,
    },
    {
      label: "",
      value: 2,
    },
  ],
};

export const orgValues = {
  [`${PaymentUsage.INSURANCE}`]: [
    {
      name: "Агис Даатгал",
      icon: `${logos}AgisInsur.png`,
      value: "agis",
    },
    {
      name: "Агула Даатгал",
      icon: `${logos}AgulaInsur.jpg`,
      value: "agula",
    },
  ],
  [`${PaymentUsage.LOAN}`]: [
    {
      name: "68 Зээлийн төв",
      icon: `${logos}68LendCenter.jpg`,
      value: "68",
    },
    {
      name: "Хаан Монгол Инвест ББСБ",
      icon: `${logos}KhaanMongolInvest.png`,
      value: "khaanmongol",
    },
  ],
  [`${PaymentUsage.VALUE}`]: [
    {
      name: "Eunit",
      icon: logoMiniBlue,
      value: "eunit",
    },
  ],
};
