export const locale = {
  lang: "mn",
  data: {
    GLOBAL: {
      N: "н",
      COMMITTEE: "хороо",
      APARTMENT: "Орон сууц",
      INFORMATION: "Мэдээлэл",
    },
    NAVBAR: {
      HOME: "Нүүр",
      ESTIMATE: "Үнэлгээ",
      WALLET: "Хэтэвч",
      CONTACT: "Холбогдох",
      DATA: "Дата",
      LOGIN: "Нэвтрэх",
      PROFILE: "Profile",
      REALSTATE_INFORMATION: "орон сууцны мэдээлэл",
      CAR: "Машины үнэлгээ",
    },
    ERROR_MESSAGES: {
      SUCCESS: "Амжилттай",
      ERROR_OCCURED: "Алдаа гарлаа",
      TRY_AGAIN: "Дахин оролдоно уу",
      COOKIE_EXPIRED: "Cookie expired",
      INFO: "Мэдэгдэл",
    },
    FILTER_ATTRIBUTE: {
      MIN: "Доод",
      MAX: "Дээд",
      M_SQUERE: "м.кв",
      TOTAL: "нийт",
      PRICE: "үнэ",
      SEARCH: "Хайх",
      SUGGESTED_FILTER: "Санал болгож буй шүүлтүүрүүд",
      DELETE: "Устгах",
      CLEAR: "Арилгах",
    },
    REPORT_TEXT: {
      APARTMENT_REQUEST_INFO: "Орон сууцны үнэлгээ гаргуулах мэдээлэл",
      OWNER_PERSONAL_INFO: "Эзэмшигчийн хувийн мэдээлэл",
      FIRST_NAME: "Нэр",
      LAST_NAME: "Овог",
      REGISTER: "Регистер",
      APARTMENT_DESCRIPTION: "Орон сууцны дэлгэрэнгүй мэдээлэл",
      DISTRICT_CHOOSE: "Орон сууцны дэлгэрэнгүй мэдээлэл",
      TOWN_CHOOSE: "Хотхоны байршил сонгох",
      LOCATION_CHOOSE: "Байршил сонгох",
      CERTIFICATE_NUMBER: "Гэрчилгээний дугаар",
      FLOOR: "Давхар",
      DOOR_NUMBER: "Хаалганы дугаар",
      OPERATION: "Ашиглалтанд орсон он",
      AREA: "Талбайн хэмжээ",
      REAL_STATE_CERTIFICATE: "Үл хөдлөх хөрөнгийн гэрчилгээ",
      SIGNATURE: "Гарын үсэг зурах хэсэг",
      PAY: "Төлбөр төлөх",
    },
    REVIEW_TEXT: {
      APARTMENT_AVARAGE_PRICE: "Улаанбаатар хотын орон сууцны дундаж үнэлгээ",
      DEFINITION: "Тодорхойлолт",
      GARAGE: "Гараж",
      PAYMENT_CONDITION: "Төлбөрийн нөхцөл",
      AREA: "Талбай",
      LOCATION: "Байршил",
      AVARAGE_PRICE: "Дундаж үнэлгээ",
      GENERAL_INFO: "Үндсэн мэдээлэл",
      FLOOR: "Барилгын давхар",
      SEVERAL_FLOOR: "Сонирхож буй давхар",
      OPERATION: "Ашиглалтанд орсон он",
    },

    INPUT: { PLACEHOLDER: "{{value}}" },
  },
};
