import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "@/styles/globals.scss";
import { logoMiniWhite } from "@/utils/assets";
import { APIProvider } from "@vis.gl/react-google-maps";
import Head from "next/head";
import Navbar from "@/components/navbar";
import { AppWrapper, useAppContext } from "./_context";
import { Providers } from "./_providers/chakra.provider";
// import { fonts } from "./_fonts/rubik";
import NextAuthProvider from "./_context/auth";

import ScrollTop from "@/components/global/scrollTop";

import { Suspense } from "react";
import Loading from "./loading";
import { headers } from "next/headers";
import AdminBar from "@/components/navbar/adminBar";

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Eunit - Монголын зарын сайт",
    template: "Eunit | %s",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerList = headers();
  const referer = headerList.get("referer");

  return (
    // <html lang="en" className={fonts.rubik.variable}>
    <html lang="en">
      <Head>
        <link
          rel=" shortcut icon"
          href={logoMiniWhite}
          type="image/png"
          sizes="32x32"
        />
      </Head>
      <body>
        <NextAuthProvider>
          <Providers>
            <AppWrapper>
              <Suspense fallback={<Loading />}>
                {referer?.includes("admin") ? <AdminBar /> : <Navbar />}
                {children}

                <ScrollTop />
              </Suspense>
            </AppWrapper>
          </Providers>
        </NextAuthProvider>
      </body>
    </html>
  );
}
